# Generated by Django 5.2.5 on 2025-08-20 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost_per_kg', models.FloatField()),
                ('protein', models.FloatField()),
                ('energy', models.FloatField()),
                ('calcium', models.FloatField(blank=True, null=True)),
                ('phosphorus', models.FloatField(blank=True, null=True)),
                ('fiber', models.FloatField(blank=True, null=True)),
                ('lysine', models.FloatField(blank=True, null=True)),
                ('methionine', models.FloatField(blank=True, null=True)),
                ('min_inclusion', models.FloatField(default=0)),
                ('max_inclusion', models.FloatField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='RationFormulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('protein_req', models.FloatField()),
                ('energy_req', models.FloatField()),
                ('calcium_req', models.FloatField(blank=True, null=True)),
                ('phosphorus_req', models.FloatField(blank=True, null=True)),
                ('fiber_req', models.FloatField(blank=True, null=True)),
                ('lysine_req', models.FloatField(blank=True, null=True)),
                ('methionine_req', models.FloatField(blank=True, null=True)),
                ('total_cost', models.FloatField()),
                ('animal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rationapp.animaltype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormulationIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_kg', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rationapp.ingredient')),
                ('formulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='rationapp.rationformulation')),
            ],
        ),
    ]
