# Generated by Django 5.2.5 on 2025-08-21 03:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rationapp', '0002_populate_initial_ingredients'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='FormulationIngredient',
            new_name='RationIngredient',
        ),
        migrations.RemoveField(
            model_name='rationformulation',
            name='animal_type',
        ),
        migrations.RenameField(
            model_name='rationformulation',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='rationformulation',
            name='calcium_req',
        ),
        migrations.RemoveField(
            model_name='rationformulation',
            name='energy_req',
        ),
        migrations.RemoveField(
            model_name='rationformulation',
            name='fiber_req',
        ),
        migrations.RemoveField(
            model_name='rationformulation',
            name='lysine_req',
        ),
        migrations.RemoveField(
            model_name='rationformulation',
            name='methionine_req',
        ),
        migrations.RemoveField(
            model_name='rationformulation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='rationformulation',
            name='phosphorus_req',
        ),
        migrations.RemoveField(
            model_name='rationformulation',
            name='protein_req',
        ),
        migrations.AddField(
            model_name='rationformulation',
            name='total_weight',
            field=models.FloatField(default=0.0, help_text='Total feed (Kg)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='energy',
            field=models.FloatField(help_text='Energy (Kcal/kg)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='max_inclusion',
            field=models.FloatField(default=100, help_text='Maximum inclusion rate (%)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='min_inclusion',
            field=models.FloatField(default=0, help_text='Minimum inclusion rate (%)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='protein',
            field=models.FloatField(help_text='Crude protein (%)'),
        ),
        migrations.AddField(
            model_name='rationformulation',
            name='animal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rationapp.animal'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FeedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_types', to='rationapp.animal')),
            ],
        ),
        migrations.CreateModel(
            name='FeedIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inclusion_rate', models.FloatField(help_text='Default inclusion rate (%)')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rationapp.ingredient')),
                ('feed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='rationapp.feedtype')),
            ],
        ),
        migrations.AddField(
            model_name='rationformulation',
            name='feed_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rationapp.feedtype'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserAvailableIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_weight', models.FloatField(help_text='Available weight (Kg)')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rationapp.ingredient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AnimalType',
        ),
    ]
