# Generated by Django 5.2.5 on 2025-08-21 04:15

from django.db import migrations


def populate_animals_and_feedtypes(apps, schema_editor):
    Animal = apps.get_model("rationapp", "Animal")
    FeedType = apps.get_model("rationapp", "FeedType")

    # Animal types
    animals = [
        ("Dairy Cattle", "Cows kept for milk production"),
        ("Beef Cattle", "Cows kept for beef production"),
        ("Goats", "Goats for milk or meat"),
        ("Sheep", "Wool and meat sheep"),
        ("Poultry - Layers", "Egg-producing chickens"),
        ("Poultry - Broilers", "Meat-producing chickens"),
        ("Pigs", "Swine for pork production"),
    ]

    animal_objs = {}
    for name, desc in animals:
        animal_obj, created = Animal.objects.get_or_create(name=name, defaults={"description": desc})
        animal_objs[name] = animal_obj

    # Feed types per animal
    feedtypes = {
        "Dairy Cattle": ["Lactation Feed", "Maintenance Feed", "Growth Feed"],
        "Beef Cattle": ["Fattening Feed", "Maintenance Feed"],
        "Goats": ["Milk Feed", "Meat Feed"],
        "Sheep": ["Wool Feed", "Meat Feed"],
        "Poultry - Layers": ["Starter Feed", "Grower Feed", "Developer Feed", "Layer Feed"],
        "Poultry - Broilers": ["Starter Feed", "Grower Feed", "Finisher Feed"],
        "Pigs": ["Piglet Feed", "Grower Feed", "Finisher Feed"],
    }

    for animal_name, feeds in feedtypes.items():
        animal_obj = animal_objs.get(animal_name)
        if animal_obj:
            for feed_name in feeds:
                FeedType.objects.get_or_create(name=feed_name, animal=animal_obj)


def reverse_populate(apps, schema_editor):
    FeedType = apps.get_model("rationapp", "FeedType")
    Animal = apps.get_model("rationapp", "Animal")
    FeedType.objects.all().delete()
    Animal.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("rationapp", "0003_animal_rename_formulationingredient_rationingredient_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_animals_and_feedtypes, reverse_populate),
    ]
