# Generated by Django 5.2.5 on 2025-08-18 06:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('default_unit', models.CharField(choices=[('KG', 'Kilogram'), ('BAG_50', '50 Kg Bag'), ('BAG_60', '60 Kg Bag')], default='KG', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InputCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acres', models.DecimalField(decimal_places=2, max_digits=5)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.crop')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.farmer')),
            ],
            options={
                'unique_together': {('farmer', 'crop')},
            },
        ),
        migrations.CreateModel(
            name='FarmInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('market_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.inputcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(choices=[('KG', 'Kilogram'), ('BAG_50', '50 Kg Bag'), ('BAG_60', '60 Kg Bag')], default='KG', max_length=10)),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('farmer_crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.farmercrop')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.season')),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_distributed', models.DateField(auto_now_add=True)),
                ('billed', models.BooleanField(default=False)),
                ('farmer_crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.farmercrop')),
                ('farm_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.farminput')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.season')),
            ],
        ),
        migrations.CreateModel(
            name='FarmerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date_generated', models.DateField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.farmer')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.season')),
            ],
            options={
                'unique_together': {('farmer', 'season')},
            },
        ),
    ]
